# Generated by Django 5.1.1 on 2024-10-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_category_name_category_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Breeds',
        ),
        migrations.RenameField(
            model_name='breeds',
            old_name='category',
            new_name='breed',
        ),
    ]
