# Generated by Django 5.1.1 on 2024-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_category_cats_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='owner',
            field=models.CharField(default='Unknown', max_length=40),
        ),
    ]
